name: Update Last Commit SVG

on:
  push:                # 每次提交代码时自动更新
    branches: ["**"]
  workflow_dispatch: {}  # 允许在 Actions 面板手动触发
  schedule:
    - cron: "0 */6 * * *"   # 兜底：每 6 小时也更新一次（可改 */2、*/12 等）

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # 需要完整历史获取最后一次提交时间

      - name: Generate SVG
        run: bash scripts/gen-last-commit.sh

      - name: Commit changes if any
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add assets/last-commit.svg
            git commit -m "chore: update last-commit.svg"
            git push
          else
            echo "No changes"
          fi
