name: Update Last Commit SVG

on:
  push:                # 每次推送都会更新
    branches: ["**"]
  workflow_dispatch: {}  # 允许手动触发
  schedule:
    - cron: "0 */6 * * *"  # 兜底：每 6 小时更新一次（可改 */2 等）

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 需要完整历史获取最后提交

      - name: Make script executable
        run: chmod +x scripts/gen-last-commit.sh

      - name: Generate SVG
        run: ./scripts/gen-last-commit.sh

      - name: Commit changes if any
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add assets/last-commit.svg
            git commit -m "chore: update last-commit.svg"
            git push
          else
            echo "No changes"
          fi
